config/routes.rb
Rails.application.routes.draw do

  get 'admins', to: 'admins#index', as: 'admins_index'
  get 'show/:id', to: 'admins#show', as: 'admins_show'
   get 'change/:id', to: 'admins#change', as: 'admins_change'
   get 'set_welcome/:id',  to: 'admins#set_to_about_welcome', as: 'set_welcome'
   get 'delete_about', to: 'admins#delete_adout', as: 'delete_adout'

  root 'welcome#index'
  get 'about', to: 'welcome#about', as: 'welcome_about'

  devise_for :users

  resources :posts, only: [:index, :new, :create, :destroy, :show]
  get 'about_posts', to: 'posts#about', as: 'about_posts'

  resources :folders, only: [:index, :new, :create, :destroy, :show] do
    resources :contents, except: [:index, :edit, :update, :show]
    get 'set_public/:id(.:format)', to: 'contents#public!', as: 'set_public'
  end
  get 'about_folders', to: 'folders#about', as: 'about_folders'

  get 'public', to: 'folders#public', as: 'public_folder'
  get 'about_public', to: 'folders#about_public', as: 'about_public_folders'

  # only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'post_comments/:post_id', to: 'admins#post_comments', as: 'admins_post_comments'
end

app/views/source/_footer.html.erb
<footer>
    <div class="row">
        <div class="col-lg-12">
            <p>Copyright &copy; Your Website 2014</p>
        </div>
    </div>
</footer>

app/views/source/_form.html.erb
<div class="container">
  <%= form_for @post, html: { multipart: true } do |post| %>

  <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="input-group">
      <span class="input-group-addon" id="sizing-addon1">Title</span>
      <%= post.text_field :title, :class => "form-control", :style => "width:600px", :placeholder => "Enter title here"%>
    </div><br>
    <div class="input-group">
      <span class="input-group-addon" id="sizing-addon1">Text</span>
      <%= post.text_area :text, :class => "form-control", :style => "height:200px; min-width:600px; max-width:600px;", :placeholder => "Enter text here"%>
    </div><br>

    <div class="input-group">
      <%= post.file_field :image %>
    </div><br>

    <%= post.submit "Save", class: "btn btn-primary"%>
    <% end %>
</div>

app/views/source/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" href="#">Home_Files</a> -->
      <%= link_to 'Home_Files', root_path, {:class => "navbar-brand", :style => "color:CornflowerBlue;"}%>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Features <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if user_signed_in? %><li><%= link_to 'Private Storage', folders_path %></li><% end %>
            <li><%= link_to 'Public storage', public_folder_path %></li>
            <li><%= link_to 'Family Blog', posts_path %></li>
            <li><%= link_to 'Family Dashboard', root_path %></li>
            <li role="separator" class="divider"></li>
            <!-- <li><a href="#">About our family</a></li> -->
            <li><%= link_to 'About our family', welcome_about_path %></li>
          </ul>
        </li>
        <%= render 'source/links_l.html.erb' %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% unless user_signed_in? %>
          <li><%= link_to 'Log in', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% else %>
          <%= render 'source/links_r.html.erb' %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'My account', root_path %></li>
              <% if current_user&.admin? %><li><%= link_to 'Admin Page', admins_index_path %></li><% end %>
              <li role="separator" class="divider"></li>
              <!-- <li><a href="#">Log out</a></li> -->
              <li><%= link_to 'Log out', destroy_user_session_path, :method => :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/source/_links.html.erb
<% if user_signed_in? %>
  <% if controller_name == 'posts' %>
    <li><%= link_to 'New post', new_post_path %></li>
  <% end %>
<% end %>

app/views/source/_links_l.html.erb
<% if controller_name == 'posts' %>
  <% if action_name == 'show' or action_name == 'new' or action_name == 'about' %>
  <li><%= link_to 'All posts', posts_path, :style => "color:CornflowerBlue;" %></li>
  <% end %>
  <% if action_name == 'show' and current_user&.admin? %>
    <li><%= link_to 'More about user', admins_show_path(@post.user) %></li>
  <% end %>
<% end %>
<% if controller_name == 'folders' %>
  <% if action_name == 'show' or action_name == 'new' or action_name == 'about' %>
    <li><%= link_to 'All folders', folders_path, :style => "color:CornflowerBlue;" %></li>
  <% end %>
<% end %>
<% if controller_name == 'contents' && action_name == 'new' %>
  <li><%= link_to 'All folders ', folders_path, :style => "color:CornflowerBlue;" %></li>
  <li><%= link_to '>' %></li>
  <li><%= link_to @folder.title, folder_path(@folder), :style => "color:CornflowerBlue;" %></li>
<% end %>
<% if controller_name == 'admins' && action_name == 'show' && current_user&.admin? %>
  <li><%= link_to 'All Users', admins_index_path, :style => "color:CornflowerBlue;" %></li>
<% end %>

app/views/source/_links_r.html.erb
<% if user_signed_in? %>
  <% if controller_name == 'posts' %>
    <li><%= link_to 'New post', new_post_path, :style => "color:CornflowerBlue;" %></li>
    <% if action_name == 'show' %>
      <% if current_user.admin? %><li><%= link_to 'Set as a family info', set_welcome_path(@post) %></li><% end %>
      <% if current_user.admin? or @post.user == current_user %><li><%= link_to "Delete", @post, method: :delete, data: { confirm: "Are you sure?" }, :style => "color:LightCoral ;" %></li><% end %>
    <% end %>
  <% end %>
  <% if controller_name == 'welcome' && action_name == 'about' && @post && current_user.admin? %>
    <li><%= link_to 'Delete about', delete_adout_path, :style => "color:LightCoral ;"  %></li>
  <% end %>
  <% if controller_name == 'folders' %>
    <%if action_name == 'index' %>
      <li><%= link_to 'New folder', new_folder_path, :style => "color:CornflowerBlue;" %></li>
    <% end %>
    <% if action_name == 'show' %>
      <li><%= link_to 'New file', new_folder_content_path(@folder), :style => "color:CornflowerBlue;" %></li>
      <li><%= link_to "Delete #{@folder.title}", @folder, method: :delete, data: { confirm: "Are you sure?" }, :style => "color:LightCoral ;"  %></li>
    <% end %>
  <% end %>
  <% if controller_name == 'admins' %>
    <% if action_name == 'show' and @user != current_user %>
      <li><%= link_to "#{@user.admin? ? 'Make a user!' : 'Make an admin!'}", admins_change_path(@user), :style => "color:LightCoral ;" %></li>
    <% end %>
  <% end %>
<% end %>