config/routes.rb
Rails.application.routes.draw do

  get 'admins', to: 'admins#index', as: 'admins_index'
  get 'show/:id', to: 'admins#show', as: 'admins_show'
   get 'change/:id', to: 'admins#change', as: 'admins_change'
   get 'set_welcome/:id',  to: 'admins#set_to_about_welcome', as: 'set_welcome'
   get 'delete_about', to: 'admins#delete_adout', as: 'delete_adout'

  root 'welcome#index'
  get 'about', to: 'welcome#about', as: 'welcome_about'

  devise_for :users

  resources :posts, only: [:index, :new, :create, :destroy, :show]
  get 'about_posts', to: 'posts#about', as: 'about_posts'

  resources :folders, only: [:index, :new, :create, :destroy, :show] do
    resources :contents, except: [:index, :edit, :update, :show]
    get 'set_public/:id(.:format)', to: 'contents#public!', as: 'set_public'
  end
  get 'about_folders', to: 'folders#about', as: 'about_folders'

  get 'public', to: 'folders#public', as: 'public_folder'
  get 'about_public', to: 'folders#about_public', as: 'about_public_folders'

  # only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'post_comments/:post_id', to: 'admins#post_comments', as: 'admins_post_comments'
end

app/views/admins/index.html.erb
<div class="container">
<table class="table">
  <thead class="grey">
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Post count</th>
      <th>Folders count</th>
      <th>Files count</th>
      <th>Public files count</th>
    </tr>
  </thead>
<tbody>
<% @users.each do |user| %>
  <% if user.admin? %>
    <tr class="bg-danger">
  <% else %>
    <tr class="bg-deffault">
  <% end %>
    <td><%= link_to "#{user.username}#{user == current_user ? ' [you]' : (user.admin? ? ' [admin]' : '')}", admins_show_path(user) %></td>
    <td><%= user.email %></td>
    <td><%= user.posts.count %></td>
    <td><%= user.folders.count %></td>
    <td><%= user.contents.count %></td>
    <td><%= user.contents.where(public: true).count %></td>

  </tr>
<% end %>
</tbody>
</table>
<%= will_paginate @users, renderer: BootstrapPagination::Rails %>
</div>

app/views/admins/show.html.erb
  <div class="jumbotron">
    <h2><%=  @user.username.capitalize %>
      <span class="text-danger"><%= "[admin#{':you' if @user == current_user}]" if @user.admin? %></span>
      <span class="text-success"><%= "[user]" if @user.user? %></span>
    </h2>
    <p>
      User has <%= @user.posts.count %> post(s).
    </p>
    <ul>
      <% @posts.each do |post| %>
        <li><%= link_to post.title, post_path(post) %></li>
      <% end %>

    </ul>
    <div>
      <%= will_paginate @posts %>
    </div>
  </div>