config/routes.rb
Rails.application.routes.draw do

  get 'admins', to: 'admins#index', as: 'admins_index'
  get 'show/:id', to: 'admins#show', as: 'admins_show'
   get 'change/:id', to: 'admins#change', as: 'admins_change'
   get 'set_welcome/:id',  to: 'admins#set_to_about_welcome', as: 'set_welcome'
   get 'delete_about', to: 'admins#delete_adout', as: 'delete_adout'

  root 'welcome#index'
  get 'about', to: 'welcome#about', as: 'welcome_about'

  devise_for :users

  resources :posts, only: [:index, :new, :create, :destroy, :show]
  get 'about_posts', to: 'posts#about', as: 'about_posts'

  resources :folders, only: [:index, :new, :create, :destroy, :show] do
    resources :contents, except: [:index, :edit, :update, :show]
    get 'set_public/:id(.:format)', to: 'contents#public!', as: 'set_public'
  end
  get 'about_folders', to: 'folders#about', as: 'about_folders'

  get 'public', to: 'folders#public', as: 'public_folder'
  get 'about_public', to: 'folders#about_public', as: 'about_public_folders'

  # only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'post_comments/:post_id', to: 'admins#post_comments', as: 'admins_post_comments'
end

app/models/folder.rb
# == Schema Information
#
# Table name: folders
#
#  id         :integer          not null, primary key
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#  slug       :string
#

class Folder < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :user
  has_many :contents, dependent: :destroy
  validates :title, presence: true, length: { in: 3..9 }
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_action :authenticate_user!, except: :public
  before_action :owner?, only: :set_folder
  before_action :set_folder, only: [:show, :destroy]

  def index
    @folders = current_user.folders.all.order('created_at DESC').paginate(:page => params[:page], :per_page => 12)
  end

  def new
    @folder = current_user.folders.new
  end

  def create
    @folder = current_user.folders.build(folder_params)
    if @folder.save
      redirect_to folders_path, :notice => "Your folder was succesfully created."
    else
      redirect_to new_folder_path, alert: "Error in #{@folder.errors}"
    end
  end

  def show
    @contents = @folder.contents.paginate(:page => params[:page], :per_page => 10)
  end

  def destroy
    @folder.contents.each do |content|
      FileUtils.rm_rf("public/uploads/content/content/#{content.id}")
    end
    @folder.destroy
    redirect_to folders_path, alert: "Your folder was succesfully deleted!"
  end

  def about
  end

  def about_public
  end

  def public
    @contents = Content.where(public: true).order('created_at DESC').paginate(:page => params[:page], :per_page => 12)
  end

  private
  def folder_params
    params.require(:folder).permit(:title)
  end

  def owner?
    unless current_user == Folder.friendly.find(params[:id]).user
      render file: "#{Rails.root}/public/404.html", layout: false, status: 404
    end
  end

  def set_folder
    @folder = current_user.folders.friendly.find(params[:id])
  end
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/views/folders/about.html.erb
<%= render 'about/private.html.erb' %>

app/views/folders/about_public.html.erb
<%= render 'about/public.html.erb' %>

app/views/folders/index.html.erb
<% unless @folders.empty? %>
  <div class="container">
    <div class="row text-center">
      <% @folders.each do |folder| %>
        <div class="col-md-2 portfolio-item">
          <%= link_to folder_path(folder) do %>
            <%= image_tag "folders/folder.png", class: "img-responsive" %>
          <h4>
            <%= folder.title %>
          </h4>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="row text-center">
      <div class="col-lg-12">
        <%= will_paginate @folders, renderer: BootstrapPagination::Rails %>
      </div>
    </div>
  </div>
<% else %>
  <%= render 'sorry/no_folders.html.erb' %>
<% end %>

app/views/folders/new.html.erb
<%= bootstrap_form_for(@folder) do |f| %>
  <%= f.text_field :title %>
  <%= f.submit "Create!" %>
<% end %>

app/views/folders/public.html.erb
<% unless @contents.empty? %>
<table class="table">
  <thead>
    <tr>
      <th>File Name</th>
      <th>Size</th>
      <th>Created at</th>
    </tr>
  </thead>
  <tbody>
<% @contents.each do |content| %>
  <tr>
    <td><%= link_to content.content_identifier, content.content.url %></td>
    <td class="text-muted"><%= number_to_human_size(content.content.size) %></td>
    <td class="text-muted"><%= content.created_at.strftime('%b %d, %Y') %></td>
  </tr>
<% end %>
</tbody>
</table>
<div class="row text-center">
  <div class="col-lg-12">
    <%= will_paginate @contents, renderer: BootstrapPagination::Rails %>
  </div>
</div>
<% else %>
  <%= render 'sorry/no_public.html.erb' %>
<% end %>

app/views/folders/show.html.erb
<div class="container">
  <div class="row">
      <div class="col-md-2 portfolio-item">
          <%= image_tag "folders/folder.png", class: "img-responsive" %>
      </div>

      <div class="col-md-5 portfolio-item">
        <h2>Name: <%= @folder.title %></h2>
        <h3>Created at: <%= @folder.created_at.strftime('%b %d, %Y') %></h3>
        <% unless @contents.empty? %><h3 class="text-muted">Cout of files: <%= @folder.contents.count %></h3><% else %><h4 class="text-muted">Empty Folder</h4><% end %>
      </div>
  </div>
</div>
<% unless @contents.empty? %>
<table class="table">
  <thead>
    <tr>
      <th>File Name</th>
      <th>Size</th>
      <th>Created at</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<% @contents.each do |content| %>
  <tr>
    <td><%= link_to content.content_identifier, content.content.url %></td>
    <td class="text-muted"><%= number_to_human_size(content.content.size) %></td>
    <td class="text-muted"><%= content.created_at.strftime('%b %d, %Y') %></td>
    <td><%= link_to "Delete!", [@folder, content], data: { confirm: "Are you sure?" }, method: :delete,  :style => "color:LightCoral;"  %></td>
    <td><%= link_to content.public ? 'Hide!' : 'Publish', folder_set_public_path(@folder, content), :style => "color:CornflowerBlue;"  %></td>
  </tr>
<% end %>
</tbody>
</table>
<div class="row text-center">
  <div class="col-lg-12">
    <%= will_paginate @contents, renderer: BootstrapPagination::Rails %>
  </div>
</div>
<% end %>