config/routes.rb
Rails.application.routes.draw do

  get 'admins', to: 'admins#index', as: 'admins_index'
  get 'show/:id', to: 'admins#show', as: 'admins_show'
   get 'change/:id', to: 'admins#change', as: 'admins_change'
   get 'set_welcome/:id',  to: 'admins#set_to_about_welcome', as: 'set_welcome'
   get 'delete_about', to: 'admins#delete_adout', as: 'delete_adout'

  root 'welcome#index'
  get 'about', to: 'welcome#about', as: 'welcome_about'

  devise_for :users

  resources :posts, only: [:index, :new, :create, :destroy, :show]
  get 'about_posts', to: 'posts#about', as: 'about_posts'

  resources :folders, only: [:index, :new, :create, :destroy, :show] do
    resources :contents, except: [:index, :edit, :update, :show]
    get 'set_public/:id(.:format)', to: 'contents#public!', as: 'set_public'
  end
  get 'about_folders', to: 'folders#about', as: 'about_folders'

  get 'public', to: 'folders#public', as: 'public_folder'
  get 'about_public', to: 'folders#about_public', as: 'about_public_folders'

  # only: [:new, :create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'post_comments/:post_id', to: 'admins#post_comments', as: 'admins_post_comments'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
    Post.all.each do |post|
      if post.about_welcome
        @post = post
        break
      end
    end
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<% if @post %>
  <header class="jumbotron hero-spacer" style="background-image:url(images/posts/form.jpg);">
    <h1>About our Family!!!</h1>
    <p>
      <%= @post.text %>
    </p>
    <p>
      <%= link_to image_url(@post.image) do %>
        <%= image_tag @post.image.show.url %><br>
      <% end %>
    </p>
  </header>
<% else %>
  <%= render 'sorry/no_about_welcome.html.erb' %>
<% end %>

app/views/welcome/index.html.erb
<header class="jumbotron hero-spacer" style="background-image:url(images/header.jpg);color:white;">
  <h1>Welcome to our Family!</h1>
  <p>
    This is site of our family. Here you can see our photos of last year joreny, out cat. Moreover you can read our family blog. And what is more, there is a dashboard of our social network activity.
  </p>
  <p>
    <%= link_to 'Read more about us', welcome_about_path, :class => "btn btn-primary btn-large" %>
  </p>
  </header>

  <hr>

  <div class="row text-center">
    <% if user_signed_in? %>
      <div class="col-md-3 col-sm-6 hero-feature">
        <div class="thumbnail">
          <%= link_to folders_path do %>
            <%= image_tag 'lock.jpg' %>
          <% end %>
          <div class="caption">
            <h3>Private Storage</h3>
            <p>Here you can store your files and photos.</p>
            <p>
              <div class="btn-group" role="group" aria-label="Basic example">
                <%= link_to 'Go to!', folders_path, :type => "button", :class => "btn btn-secondary btn btn-primary" %>
                <%= link_to 'More Info!', about_folders_path, :type => "button", :class => "btn btn-secondary btn btn-default" %>
              </div>
            </p>
          </div>
        </div>
      </div>
    <% end %>

    <div class="col-md-3 col-sm-6 hero-feature">
      <div class="thumbnail">
        <%= link_to public_folder_path do %>
          <%= image_tag 'public.jpg' %>
        <% end %>
        <div class="caption">
          <h3>Public Storage</h3>
          <p>Our family folder: sea, jim, pets and love.</p>
          <p>
            <div class="btn-group" role="group" aria-label="Basic example">
              <%= link_to 'Go to!', public_folder_path, :type => "button", :class => "btn btn-secondary btn btn-primary" %>
              <%= link_to 'More Info!', about_public_folders_path, :type => "button", :class => "btn btn-secondary btn btn-default" %>
            </div>
          </p>
        </div>
      </div>
    </div>

    <div class="col-md-3 col-sm-6 hero-feature">
      <div class="thumbnail">
        <%= link_to posts_path do %>
          <%= image_tag 'blog.jpg' %>
        <% end %>
        <div class="caption">
          <h3>Family Blog</h3>
          <p>Our plans, rules. tasks, wishes and thoughts.</p>
          <p>
            <div class="btn-group" role="group" aria-label="Basic example">
              <%= link_to 'Go to!', posts_path, :type => "button", :class => "btn btn-secondary btn btn-primary" %>
              <%= link_to 'More Info!', about_posts_path, :type => "button", :class => "btn btn-secondary btn btn-default" %>
            </div>
          </p>
        </div>
      </div>
    </div>

    <div class="col-md-3 col-sm-6 hero-feature">
      <div class="thumbnail">
        <%= link_to root_path do %>
          <%= image_tag 'board.jpg' %>
        <% end %>
        <div class="caption">
          <h3>Family Dashboard</h3>
          <p>Here you cam monitore our social live.</p>
          <p>
            <div class="btn-group" role="group" aria-label="Basic example">
              <%= link_to 'Go to!', root_path, :type => "button", :class => "btn btn-secondary btn btn-primary" %>
              <%= link_to 'More Info!', root_path, :type => "button", :class => "btn btn-secondary btn btn-default" %>
            </div>
          </p>
        </div>
      </div>
    </div>

  </div>